export type MasonryItem = {
  title: string,
  slug: string,
  logo?: string,
  duration: string,
  isThumb: boolean,
  type: string,
  summary?: string,
  description: string,
  languages?: string,
  frameworks?: string,
  tools?: string,
  platforms?: string,
  status?: string,
  hideOnListing?: boolean,
  private?: boolean,
}
